### ISSUE TITLE
`npm run test:unit` のテストが失敗する

### ISSUE THREAD

**Issue by gh640** [gh640/express-jest-example-ja#116]
https://github.com/gh640/express-jest-example-ja/actions/runs/8151490710

#115 で発生しました。

- #115

```bash
❯ npm run test:unit

> express-jest-example-ja@1.0.0 test:unit
> NODE_OPTIONS=--experimental-vm-modules jest __tests__/unit

 FAIL  __tests__/unit/handlers/reverse.test.js
  ● Test suite failed to run

    TypeError: page.removeListener is not a function

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/env.js:227:18)

 FAIL  __tests__/unit/handlers/hello.test.js
  ● Test suite failed to run

    TypeError: page.removeListener is not a function

      at PuppeteerEnvironment.teardown (node_modules/jest-environment-puppeteer/lib/env.js:227:18)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.432 s, estimated 1 s
Ran all test suites matching /__tests__\/unit/i.
```

**Comment by gh640** [comment]
## 過去の似たイシュー

- #10

**Comment by gh640** [comment]
`jest-puppeteer` が古いことが原因のようです。

`package.json`:

```patch
-    "jest-puppeteer": "^7.0.0",
+    "jest-puppeteer": "^10.0.1",
```

**Comment by gh640** [comment]
`jest-puppeteer` を最新版にすると解消できました。

https://github.com/gh640/express-jest-example-ja/actions/runs/8152141383
